version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app-network
    env_file:
      - .env

  ws:
    build:
      context: .
      dockerfile: Dockerfile.ws
    ports:
      - "8080:8080"
    volumes:
      - ./ws_server:/app
    networks:
      - app-network
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
