# Этап 1: сборка React
FROM node:18 as build

WORKDIR /app
COPY frontend/package*.json /app/
RUN npm install

COPY frontend /app
RUN npm run build

# Этап 2: Nginx для отдачи статики
FROM nginx:stable-alpine

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
