version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    networks:
      - app-network

  ws:
    build:
      context: .
      dockerfile: Dockerfile.ws
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.prod
    ports:
      - "80:80"
    depends_on:
      - backend
      - ws
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
